// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBwY01KEjrWvctp90nQVoRQTBoCjYA_E',
    appId: '1:731108460065:web:f62a7a0f0339913e2ac560',
    messagingSenderId: '731108460065',
    projectId: 'encuestador-bb4ab',
    authDomain: 'encuestador-bb4ab.firebaseapp.com',
    storageBucket: 'encuestador-bb4ab.firebasestorage.app',
    measurementId: 'G-M5ND147V67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkabm6ZmEBC4_DCDMJemxf-SFW6RsaORk',
    appId: '1:731108460065:android:42ca0f1cf44591d52ac560',
    messagingSenderId: '731108460065',
    projectId: 'encuestador-bb4ab',
    storageBucket: 'encuestador-bb4ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLRVKCXiDSRUMrErz7WzwQCbdE5Y9wG30',
    appId: '1:731108460065:ios:e81ba62279aede572ac560',
    messagingSenderId: '731108460065',
    projectId: 'encuestador-bb4ab',
    storageBucket: 'encuestador-bb4ab.firebasestorage.app',
    iosBundleId: 'com.example.myPwaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLRVKCXiDSRUMrErz7WzwQCbdE5Y9wG30',
    appId: '1:731108460065:ios:e81ba62279aede572ac560',
    messagingSenderId: '731108460065',
    projectId: 'encuestador-bb4ab',
    storageBucket: 'encuestador-bb4ab.firebasestorage.app',
    iosBundleId: 'com.example.myPwaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiBwY01KEjrWvctp90nQVoRQTBoCjYA_E',
    appId: '1:731108460065:web:a94c801c5b873de92ac560',
    messagingSenderId: '731108460065',
    projectId: 'encuestador-bb4ab',
    authDomain: 'encuestador-bb4ab.firebaseapp.com',
    storageBucket: 'encuestador-bb4ab.firebasestorage.app',
    measurementId: 'G-G8BC043D32',
  );
}
